version: "3.6"
volumes:
    datadb:
        external: false
services:
    nginx:
        build:
            context: ./src/nginx
        image: lin/nginx-${COMPOSE_PROJECT_NAME}
        container_name: nginx-${COMPOSE_PROJECT_NAME}
        ports:
            - 80:80
        networks:
            - app
        depends_on:
            - php
        volumes:
            - ./public:/var/www/html
            - ./src/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./src/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./target/nginx/log/:/var/log/nginx/
        env_file:
          - ./.env
        restart: unless-stopped
    php:
        build:
            context: ./src/php/
        image: lin/php-${COMPOSE_PROJECT_NAME}
        container_name: php-${COMPOSE_PROJECT_NAME}
        env_file:
          - ./.env
        expose:
            - 9000
        ports:
            - 9000:9000
        networks:
            - app
        depends_on:
            - mysql
        volumes:
            - ./public:/var/www/html
        restart: unless-stopped
    mysql:
        build:
            context: ./src/mysql
        image: lin/mysql-${COMPOSE_PROJECT_NAME}
        container_name: mysql-${COMPOSE_PROJECT_NAME}
        volumes:
            - datadb:/var/lib/mysql
        env_file:
          - ./.env
        ports:
            - 3306:3306
        networks:
            - app
        restart: unless-stopped
    glassfish:
        build:
            context: ./src/glassfish
        image: lin/glassfish-${COMPOSE_PROJECT_NAME}
        container_name: glassfish-${COMPOSE_PROJECT_NAME}
        ports:
            - 8080:8080
            - 4848:4848
            - 8181:8181
        networks:
            - app
        volumes:
            - ./target:/usr/local/glassfish5
        env_file:
          - ./glassfish.env
networks:
    app:
        driver: bridge
        name: developer-network-$COMPOSE_PROJECT_NAME